# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines". This is also required in order to use the
# cache configured below.
sudo: false

cache:
  directories:
    - $HOME/.m2/repository

language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: |
  java -version
  ant test

